version: '2'

services:
  tracker:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8765
        --access-logfile -
        --reload
        "tracker.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/tracker'
    ports:
      - '8765:8765' # remove left site in case you want to be able to create instances of tracker
